# Generated by Django 3.1.4 on 2021-04-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200621_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='c_type',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
